const mongoose = require('mongoose');

/**
 * In-App Notifications (DOC-18)
 * -------------------------------------------------------------------------
 *
 * WHY THIS IS A SEPARATE MODEL FROM RequestActivity (DOC-17)
 * DOC-17's RequestActivity answers "what happened to this Request?" - a
 * single, shared, chronological record per Request, visible to everyone
 * authorized to view that Request. This model answers a different
 * question: "what does THIS SPECIFIC USER need to know?" - one row per
 * (event, recipient) pair, visible ONLY to that recipient. The two are
 * deliberately never merged into one collection or one read model: a
 * single business event (e.g. a Manager reassigning an Operator) writes
 * exactly one RequestActivity entry but may write up to three Notification
 * documents (Employee, previous Operator, new Operator) - each with its
 * own recipient-specific title/message and its own independent read
 * state. Neither model is authoritative for the other; a notification is
 * never generated by reading RequestActivity after the fact (see
 * services/notification.service.js's own comment) - both are written
 * directly, once, from the same successful controller transition.
 *
 * WHY A SEPARATE COLLECTION, NOT AN EMBEDDED ARRAY
 * Same reasoning DOC-17/DOC-13/DOC-60 already established for this
 * project: an unbounded, ever-growing list embedded on User (or Request)
 * risks the 16MB BSON document ceiling on a long-lived account, and a
 * separate collection is what makes `{recipientId, createdAt}` and
 * `{recipientId, readAt}` indexable and cheaply paginatable.
 *
 * SCHEMA
 *   organizationId - the tenant boundary, always derived server-side from
 *     the already-authorized Request (or, for a future non-Request event,
 *     from req.user.organizationId) - NEVER from req.body/req.query/
 *     frontend state (task spec section 7).
 *   recipientId - who this notification is FOR. Always a real User._id in
 *     the SAME organizationId - never client-suppliable (task spec
 *     section 15: "Do not let clients supply recipientId").
 *   actorId - who performed the action that caused this notification, if
 *     any. Optional (`null`) for a hypothetical future system-generated
 *     notification with no human actor (task spec section 38 item 5:
 *     "actor optional when system-generated") - every notification type
 *     actually implemented in this version always has a real actor, but
 *     the schema does not hard-require one, so a future system-generated
 *     type (e.g. an overdue-SLA sweep) never needs a schema change.
 *   requestId - which Request this notification is about, if any.
 *     Optional for the same forward-compatibility reason as `actorId` -
 *     every type implemented in this version is Request-related and
 *     always sets this, but the schema itself does not assume every
 *     future notification type will be.
 *   type - controlled enum (NOTIFICATION_TYPES below) - never an arbitrary
 *     free-text event (task spec section 4/37).
 *   title / message - short, already-safe, human-readable strings
 *     SNAPSHOTTED at write time (task spec section 11: "storing safe
 *     title/message fields is acceptable for notification snapshots").
 *     Deliberately NOT limited to raw structured data the way DOC-17
 *     stores oldValue/newValue - a notification is read once, briefly, in
 *     a small dropdown, and there is no future "reformat every historical
 *     notification" requirement the way DOC-17 anticipates for its
 *     longer-lived Timeline - so a plain finished sentence, built once by
 *     notification.service.js's own small set of message-builder
 *     functions (never scattered ad hoc across controllers), is the
 *     simpler, sufficient choice here. The Request's own title is
 *     reflected into `message`/`metadata.requestTitle`, never its full
 *     description body (task spec: "Do not store sensitive Request
 *     description bodies").
 *   metadata - compact, structured, already-safe extra context (e.g.
 *     `{requestTitle, operatorName, previousOperatorName, newStatus,
 *     cancelReason}`) - the same "never a secret, never a raw storage
 *     internal" discipline DOC-17's own metadata already follows. Never a
 *     password, token, S3/GridFS internal, or MongoDB credential.
 *   readAt - `null` while unread; set to the real timestamp the moment the
 *     recipient marks it read (task spec section 12: "Use readAt: null
 *     for unread... Do not use only a Boolean if timestamp is easy and
 *     useful.").
 *
 * REQUEST IDENTIFICATION (task spec section 10)
 * DOC-63 "Human-Friendly Request ID" does not exist yet - this schema
 * never invents a fake permanent request number. `requestId` (the real
 * ObjectId) plus `metadata.requestTitle` (a plain snapshotted string) are
 * everything a notification needs to identify a Request today. If DOC-63
 * ships later, it can add a `requestNumber` field to `metadata` (or a new
 * top-level field) without any change to this schema's existing fields -
 * `metadata` is already a free-form Mixed object for exactly this reason.
 *
 * IMMUTABILITY
 * Like RequestActivity, a Notification is never edited by a user - the
 * ONLY field any API endpoint is ever allowed to change after creation is
 * `readAt` (via the mark-read/mark-all-read endpoints), and only by its
 * own recipient. There is no PATCH for title/message/metadata, and no
 * DELETE endpoint at all in this Sprint (task spec section 13: "Do not
 * allow normal users to delete historical notifications... unless there
 * is already a clear product requirement" - there is not).
 */
const NOTIFICATION_TYPES = [
  'REQUEST_ASSIGNED',
  'REQUEST_REASSIGNED',
  'REQUEST_UNASSIGNED',
  'REQUEST_STATUS_CHANGED',
  'REQUEST_RESOLVED',
  'REQUEST_REOPENED',
  'REQUEST_CANCELLED',
];

const notificationSchema = new mongoose.Schema(
  {
    organizationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Organization',
      required: true,
      index: true,
    },
    recipientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    actorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    requestId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Request',
      default: null,
      index: true,
    },
    type: {
      type: String,
      enum: NOTIFICATION_TYPES,
      required: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: [200, 'Notification title must be at most 200 characters.'],
    },
    message: {
      type: String,
      required: true,
      trim: true,
      maxlength: [500, 'Notification message must be at most 500 characters.'],
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: () => ({}),
    },
    readAt: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true },
);

// Task spec section 36 - "add sensible indexes... do not add excessive
// indexes". Both compound indexes below lead with `recipientId` (every
// real query this feature runs is scoped to "one recipient's own
// notifications", never a cross-recipient scan) and mirror the two actual
// query shapes: the notification LIST (newest-first, optionally further
// filtered in-memory-cheap by readAt) and the UNREAD-COUNT / unread-list
// query (`recipientId` + `readAt: null`, ordered newest-first). No
// separate `organizationId`-only index is added - every real query already
// includes `recipientId`, which is far more selective, so an
// organization-wide index would add write overhead for no query this
// feature actually performs.
notificationSchema.index({ recipientId: 1, createdAt: -1 });
notificationSchema.index({ recipientId: 1, readAt: 1, createdAt: -1 });

module.exports = mongoose.model('Notification', notificationSchema);
module.exports.NOTIFICATION_TYPES = NOTIFICATION_TYPES;
